INSERT INTO Account("FIRST_NAME","LAST_NAME","ACCOUNT_NUMBER") VALUES ('John','Doe',1234);
INSERT INTO Account("FIRST_NAME","LAST_NAME","ACCOUNT_NUMBER") VALUES ('Jane','Doe',1235);
INSERT INTO Account("FIRST_NAME","LAST_NAME","ACCOUNT_NUMBER") VALUES ('Jim','Taylor',1236);